version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
    command:
      redis-server --save 20 1 --loglevel warning --protected-mode no
      # --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data/redis
    networks:
      - apps

  user:
    # Build image from current dir
    build: .
    ports:
      - 5111:5111
    env_file: '.env'
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - apps
    links:
      - redis

volumes:
  cache:
    driver: local

networks:
  apps:
    driver: bridge
